[package]
name = "llvm_profparser"
version = "0.1.0"
authors = ["xd009642 <danielmckenna93@gmail.com>"]
edition = "2018"

[features]
default = ["cli"]
cli = ["structopt"]

[dependencies]
flate2 = "1.0"
leb128 = "0.2.4"
nom = "6"
md5 = "0.7"
structopt = { version = "0.3.21", optional = true }

[[bin]]
name = "llvm_profparser"
required-features = ["cli"]

[dev-dependencies]
assert_cmd = "1"
pretty_assertions = "0.7"
